// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5cxppSBT70ShfT7wDheqX2sK4rCyvY0',
    appId: '1:613431270554:android:9973a24094a8debfeb9323',
    messagingSenderId: '613431270554',
    projectId: 'nova-wallet-d5713',
    databaseURL: 'https://nova-wallet-d5713-default-rtdb.firebaseio.com',
    storageBucket: 'nova-wallet-d5713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzoVWUyfOm7aAcsQL6kdvyFDh4U5wYlp4',
    appId: '1:613431270554:ios:af86919ac34b0bf0eb9323',
    messagingSenderId: '613431270554',
    projectId: 'nova-wallet-d5713',
    databaseURL: 'https://nova-wallet-d5713-default-rtdb.firebaseio.com',
    storageBucket: 'nova-wallet-d5713.firebasestorage.app',
    iosClientId: '613431270554-c6tv29aag43i0c0l4fli1ksf0o31v0f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.novaWallet',
  );
}
